---
- name: Create a Notification Template
  hosts: localhost

  tasks:

    - name: Create Notification Template
      awx.awx.notification_template:
        name: "DO467 CH5 Demo E-mail Notification"
        notification_type: email
        notification_configuration:
          sender: gomathiselvi@gmail.com 
          recipients:
            - gosriniv@redhat.com 
          host: localhost
          port: 25
          use_ssl: no
          use_tls: no
        organization: Red Hat Training
        controller_username: admin
        controller_password: redhat
        controller_host: https://google.com
        validate_certs: false
        state: present
