---
- hosts: eos
  connection: network_cli
  gather_facts: false
  tasks:

  - name: Merge given VLAN attributes with device configuration
    eos_lldp_global:
        config:
          timer: 3000
          holdtime: 100
          reinit: 5
          tlv_select:
            management_address: False
            port_description: False
            system_description: True
    become: yes
    tags: "Merged"

  - name: Del
    eos_lldp_global:
      state: deleted
    become: yes
    tags: "Deleted"


  - name: Replace given VLAN attributes with device configuration
    eos_lldp_global:
        config:
          reinit: 7
          holdtime: 300
          timer: 5000
          tlv_select:
            management_address: False
            port_description: True
            system_description: True
    become: yes
    tags: "Replaced"

