---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
#  - name: Merge given VLAN attributes with device configuration
#    eos_l3_interfaces:
#      config:
#        - name : Ethernet1
#          ipv4:
#            - address: 113.1.1.1/24
#      state: replaced

    - name: Override given VLAN attributes with device configuration
      eos_interfaces:
        config:
          - name: Ethernet2
            description: "Ansible"
        state: merged
      become: yes



#- name: TURN ON HTTPAPI CONNECTION PLUGINS
#  hosts: eos
#  gather_facts: false
#  tasks:
#    - name: TURN ON EAPI
#      vars:
#        ansible_connection: network_cli
#      eos_eapi:
