---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run cli_command on Arista and display results
      block:
      - name: Run cli_command on Arista
        cli_command:
          command: show ip int br
        register: result

      - name: Display result to terminal window
        debug:
          var: result.changed
      when: ansible_network_os == 'eos'
