---
- hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Merge given VLAN attributes with device configuration
    eos_lldp_global:
      state: deleted

#    - name: Override given VLAN attributes with device configuration
#      eos_interfaces:
#        config:
#          - name: loopback20
#            description: "Virtualinterface20"
#        state: overridden



#- name: TURN ON HTTPAPI CONNECTION PLUGINS
#  hosts: eos
#  gather_facts: false
#  tasks:
#    - name: TURN ON EAPI
#      vars:
#        ansible_connection: network_cli
#      eos_eapi:
