---
- hosts: eos
  connection: network_cli
  gather_facts: false
  tasks:
  - import_role:
      name: /home/gosriniv/workspace/MODULES
      
  - name: Facts
    eos_facts: 
      gather_subset:
        - min 
      gather_network_resources: static_routes
    tags:
      - facts
