---
- hosts: nxos
  gather_facts: false
  connection: network_cli
  vars:
    new_vlans: "150-152"

  tasks:
  - name: Merge given VLAN attributes with device configuration
    nxos_l2_interfaces:
      config:
        - name: Ethernet1/3
          trunk:
            allowed_vlans: " {{new_vlans }}"
      state: merged

#    - name: Override given VLAN attributes with device configuration
#      eos_interfaces:
#        config:
#          - name: loopback20
#            description: "Virtualinterface20"
#        state: overridden



#- name: TURN ON HTTPAPI CONNECTION PLUGINS
#  hosts: eos
#  gather_facts: false
#  tasks:
#    - name: TURN ON EAPI
#      vars:
#        ansible_connection: network_cli
#      eos_eapi:
