---
- hosts: nxos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Capture Commands from Device
      nxos_command:
        commands:
          - show interface
      register: result

    - name: Display result
      debug:
        var: result.stdout_lines

