---
- hosts: iosxr
  gather_facts: false
  connection: network_cli

  tasks:
    - name: configure interface settings
      eos_config:
        lines:
          - description test interface
          - ip address 172.31.1.1 255.255.255.0
        parents: interface GigabitEthernet0/0/0/0

