---
- hosts: nxos
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Trial Configuration 
    cli_config: 
      config: |
        #NxOS
        hostname SWITCh
        feature lldp
        lldp holdtime 19
        lldp reinit 1
        lldp timer 23
        lldp portid-subtype 0
        no lldp tlv-select system-name
        no lldp tlv-select management-address v4
        no lldp tlv-select power-management
    tags:
      - nxos
  
  - debug: var=result
    tags: print
