---
- hosts: ios
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Merge provided configuration with device configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet0/3
            description: 'no' 

    - name: Gather
      ios_facts:
        gather_subset: all

    - name: Display result
      debug:
        var: ansible_net_interfaces['GigabitEthernet0/3']['description']
