---
- hosts: ios
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "TASK 1: Setup iBGP Peer"
      ios_bgp: &classful
        config:
          bgp_as: 64496
          router_id: 10.0.0.3
          log_neighbor_changes: true
          neighbors:
            - neighbor: 198.51.100.2
              remote_as: 64496
              enabled: true
              timers:
                keepalive: 15
                holdtime: 45
                min_neighbor_holdtime: 5
              description: R4
          networks:
            - prefix: 198.51.100.0
              masklen: 22
            - prefix: 203.0.113.0
              masklen: 8
          address_family:
            - afi: ipv4
              safi: unicast
              neighbors:
                - neighbor: 198.51.100.2
                  activate: yes
                  next_hop_self: yes
        operation: merge
      register: result
 
    - assert:
        that:
          - 'result.changed == true'
          - "'router bgp 64496' in result.commands"
          - "'address-family ipv4' in result.commands"
          - "'network 198.51.100.0 mask 255.255.254.0' in result.commands"
          - "'network 203.0.113.0' in result.commands"

    - name: Configure BGP neighbors with classful boundary (idempotent)
      ios_bgp: *classful
      register: result

    - assert:
        that:
          - 'result.changed == false'

