---
- hosts: ios
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure BGP neighbors under address family mode
      ios_bgp: &af_nbr
      operation: merge
      config:
          bgp_as: 64496
          router_id: 10.0.0.3
          log_neighbor_changes: true
          neighbors:
            - neighbor: 198.51.100.2
              remote_as: 64496
              enabled: true
              timers:
                keepalive: 15
                holdtime: 45
                min_neighbor_holdtime: 5
              description: R4
          networks:
            - prefix: 198.51.100.0
              masklen: 23
            - prefix: 203.0.113.0
              masklen: 24
          address_family:
            - afi: ipv4
              safi: unicast
              neighbors:
                - neighbor: 198.51.100.2
                  activate: yes
                  next_hop_self: yes

      register: result
    - name: Display result
      debug:
        var: result.stdout



#    - assert:
#        that:
#          - 'result.changed == true'
#          - "'router bgp 64496' in result.commands"
 #         - "'address-family ipv4' in result.commands"
#          - "'neighbor network 198.51.100.0 mask 255.255.254.0' in result.commands"
#          - "'neighbor 203.0.113.0' in result.commands"
  tasks:
    - name: Configure BGP neighbors under address family mode (idempotent)
      ios_bgp: *af_nbr
      register: result

    - assert:
        that:
          - 'result.changed == false'
